# -*- coding: utf-8 -*-

{
    'name': 'Sky Heights',
    'version': '1.0',
    'sequence': '0',
    'website': 'https://www.iskydev.com',
    'author': 'iSky Development Team',
    'summary': 'Real Estate Sky Heights',
    'description': """

""",
    'depends': ['project',
                'sale',
                'isky_hr_kpi',
                'account_accountant',
                'purchase',
                'sales_team',
                'product',
                'hr_modifications_real_estate',
                'isky_account_prepayment_extension',
                'analytic',
                'crm',
                'sale_crm','hr_expense'],
    'data': [
        'security/real_estate_security.xml',
        'security/ir.model.access.csv',
        'wizard/real_state_property_status.xml',
        'sequences/real_estate_sequences.xml',
        'views/real_estate_commission_conf.xml',
        'views/real_estate_commission_wizard.xml',
        'views/real_estate_fill_payment_lines_wizard.xml',
        'views/real_estate_property_view.xml',
        'views/real_estate_sales_order_view.xml',
        'views/real_estate_pay_strategy.xml',
        'views/real_estate_project_view.xml',
        'views/real_estate_reservation.xml',
        'views/real_estate_partners_view.xml',
        'views/real_estate_inherit_opportunity_view.xml',
        'views/real_estate_account_move_line_view.xml',
        'views/real_estate_account_invoice.xml',
        'views/real_estate_server_actions.xml',
        'views/real_estate_sales_team_view.xml',
        'views/real_estate_sales_person_view.xml',
        'wizard/real_estate_rejected_check_view.xml',
        # 'reports/report_property_reservation.xml',
        'reports/payment_strategies_report.xml',
        'reports/payment_detail_report.xml',
        # 'reports/report_property_reservation_eng.xml',
        'reports/reservation_report.xml',
        'views/reservation_payment_report_view.xml',
        'views/real_estate_purchase_inherit_view.xml',
        'views/real_estate_inherit_account_journal_view.xml',
        'wizard/select_clerk_wizard.xml',
        'views/sky_height_settings_view.xml',
        'views/real_estate_brokers_view.xml',
        'views/real_estate_sale_config_view.xml',
        'views/menus.xml',
    ],

    'installable': True,
    'auto_install': False,
}
