from . import real_estate_crm_to_opp_partner
from . import real_estate_commision_wizard
from . import real_estate_fill_payment_lines
from . import real_estate_account_invoice
from . import real_estate_commision_conf
from . import real_estate_property
from . import real_estate_project
from . import real_estate_sale_order
from . import real_estate_pay_strategy
from . import real_estate_reservation
from . import real_estate_res_partner
from . import real_estate_brokers
from . import real_estate_inherit_opportunity
from . import real_estate_account_move_line
from . import real_estate_res_users
from . import real_estate_inherit_account_journal
from . import real_estate_settings
from . import real_estate_hr_employee
from . import real_estate_sale_config

